### ISSUE TITLE
Install on a different computer

### ISSUE THREAD

**Issue by msslava** [BroadcastVision/webCG#2]
Hello, 
I read about the installation and there is:

> Install webCG on a diffrent computer and proper setup of the web server. Read more here

link does not work.
I want to use the LAMP (Ubuntu 18.04) and install the web server on another computer.
But I can not get it to work yet.
Thanks!

**Comment by BroadcastVision** [comment]
Please follow the conversation i did on the topic here:
https://web.archive.org/web/20180523001117/http://casparcg.com/forum/viewtopic.php?f=9&t=3938
